### ISSUE TITLE
Include license in project_service

### ISSUE THREAD

**Issue by kurtlewis** [zacharysang/flock#13]
https://github.com/priologic/easyrtc/blob/master/LICENSE

**Comment by zacharysang** [comment]
So looks like in the easyrtc.js file we are using, the license is already included. This leaves project_service/app.js which uses the demo implementation, but will soon be stripped down enough that I don't think we would include this license there (we would just be importing easyrtc and using that node module). Does this sound right that we shouldn't need to include a module's license if we're using the module's functions for our socket server, app.js?

**Comment by zacharysang** [comment]
It is provided by them, but not really part of the module. It's really just boilerplate, which I think does not need the license. I still need to add stuff specific to our project, but see the code below for what the minimal version looks like. It is mostly just a generic express app that imports the easyrtc library and shows how it can be integrated with an express server:

```
// Load required modules
let dotenv = require('dotenv');
let fs = require('fs');

var http    = require("http");              // http server core module
let https    = require("https");
var express = require("express");           // web framework external module
var serveStatic = require('serve-static');  // serve static files
var socketIo = require("socket.io");        // web socket external module

// initialize dotenv variables
dotenv.config();

var easyrtc = require("easyrtc");

// Set process name
process.title = "node-easyrtc";

// Setup and configure Express http server. Expect a subfolder called "static" to be the web root.
var app = express();

// TODO this should only happen in the dev environment
app.use(express.static("../master/flock_server"));

/* configure https options
let options = {
    key: fs.readFileSync(process.env["KEY_PATH"]),
    cert: fs.readFileSync(process.env["CERT_PATH"])
};
*/

// Start Express http server on port 8080
var webServer = http.createServer(app);

// Start Socket.io so it attaches itself to Express server
var socketServer = socketIo.listen(webServer, {"log level":1});

easyrtc.setOption("logLevel", "debug");

// Start EasyRTC server
var rtc = easyrtc.listen(app, socketServer, null, function(err, rtcRef) {
    console.log("Initiated");
});

// Listen on port 8080
webServer.listen(4002, function () {
    console.log('listening on http://localhost:4002');
});

```
