### ISSUE TITLE
Communication from project service to master

### ISSUE THREAD

**Issue by kurtlewis** [zacharysang/flock#35]
The project service should send updates to the master service. The functionality already exists on the master service.

Send a POST request to the url in the env var `FLOCK_COMM_URL` with the required param `secret_key` (in the env var `FLOCK_PROJECT_SECRET`) and the optional param `worker_count`.

I can add new fields if we come up with use cases for them.

**Comment by zacharysang** [comment]
Could you give an example of the value `FLOCK_COMM_URL` might take? (I'd like to be able to see if it includes like the protocol and trailing slashes, etc..).

Also, is`secret_key` just like the api key/token?

**Comment by kurtlewis** [comment]
`FLOCK_COMM_URL` is just the url to send a POST request to. The exact formatting would depend on what library you use to do it, but if just send me json with the above values that'd be great.

`secret_key` is like an api token on a per project basis that is only used for interactions between the project service and master service.
